name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd Example
          ls -la
          xcodebuild -sdk iphonesimulator -configuration Debug build
