name: Xcode - Build and Analyze

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Build
        env:
          scheme: ${{ 'default' }}
        run: |
          cd ./Example
          pod install
          xcodebuild build
